version: '3.8'

services:
  solr1:
    image: solr:8.8.2
    volumes:
      - ./scripts/wait-for-it.sh:/usr/bin/wait-for-it.sh
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    restart: always
    ports:
      - "8981:8983"
    networks:
      - solr
      - observabilitysandbox
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  solr2:
    image: solr:8.8.2
    volumes:
      - ./scripts/wait-for-it.sh:/usr/bin/wait-for-it.sh
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    restart: always
    ports:
      - "8982:8983"
    networks:
      - solr
      - observabilitysandbox
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  solr3:
    image: solr:8.8.2
    volumes:
      - ./scripts/wait-for-it.sh:/usr/bin/wait-for-it.sh
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    restart: always
    ports:
      - "8983:8983"
    networks:
      - solr
      - observabilitysandbox
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  zoo1:
    image: zookeeper:3.6.2
    hostname: zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    restart: always
    ports:
      - 2181:2181
      - 7001:7000
    networks:
      - solr
      - observabilitysandbox

  zoo2:
    image: zookeeper:3.6.2
    hostname: zoo2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    restart: always
    ports:
      - 2182:2181
      - 7002:7000
    networks:
      - solr
      - observabilitysandbox

  zoo3:
    image: zookeeper:3.6.2
    hostname: zoo3
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    restart: always
    ports:
      - 2183:2181
      - 7003:7000
    networks:
      - solr
      - observabilitysandbox

  solr-exporter:
    image: solr:8.8.2
    volumes:
      - ./scripts/wait-for-it.sh:/usr/bin/wait-for-it.sh
    command: /bin/bash -c "/usr/bin/wait-for-it.sh -h solr1 -p 8983 -t 0 && /opt/solr/contrib/prometheus-exporter/bin/solr-exporter -p 9854 -z zoo1:2181 -f /opt/solr/contrib/prometheus-exporter/conf/solr-exporter-config.xml -n 3"
    ports:
      - 9854:9854
    networks:
      - solr
      - observabilitysandbox

networks:
  solr:
  observabilitysandbox:
    name: observabilitysandbox
    external: true
